task_tracker_2/lib/task_tracker_2_web/router.ex
defmodule TaskTracker2Web.Router do
  use TaskTracker2Web, :router

  import TaskTracker2Web.Plugs.GetCurrentUser

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    # After fetch_session in the browser pipeline:
    plug :get_current_user
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Below the pipeline
  # def get_current_user(conn, _params) do
  #   # TODO: Move this function out of the router module.
  #   user_id = get_session(conn, :user_id)
  #   user = TaskTracker2.Accounts.get_user(user_id || -1)
  #   IO.puts "*************"
  #   IO.inspect user;
  #   assign(conn, :current_user, user)
  # end

  scope "/", TaskTracker2Web do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    resources "/tasks", TaskController do
      get "/slotedit", TaskController, :slot_edit, as: :slot_edit
    end
    # resources "/tasks", TaskController
    post "/session", SessionController, :create
    delete "/session", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", TaskTracker2Web do
    pipe_through :api
    resources "/slots", SlotController, except: [:new, :edit]
  end
end

task_tracker_2/lib/task_tracker_2/accounts/user.ex
defmodule TaskTracker2.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias TaskTracker2.Accounts.User


  schema "users" do
    field :email, :string
    field :name, :string
    belongs_to :manager, TaskTracker2.Accounts.User

    timestamps()
  end
  @required_fields ~w()
  @optional_fields ~w(name email user_id access_token access_token_expires_at refresh_token)

  @doc false
  def changeset(%User{} = user, attrs) do
    user
    |> cast(attrs, [:email, :name, :manager_id])
    |> validate_required([:email, :name])
  end
end

task_tracker_2/lib/task_tracker_2_web/controllers/user_controller.ex
defmodule TaskTracker2Web.UserController do
  use TaskTracker2Web, :controller

  alias TaskTracker2.Accounts
  alias TaskTracker2.Accounts.User

  def index(conn, _params) do
    users = Accounts.list_users()
    render(conn, "index.html", users: users);
  end

  def new(conn, params) do
    IO.puts "------------------";
    IO.inspect conn;
    user_ids = Accounts.get_user_id_list();
    users = Accounts.list_users();
    changeset = Accounts.change_user(%User{})
    render(conn, "new.html", changeset: changeset, users: users, user_ids: user_ids)
  end


  def create(conn, %{"user" => user_params}) do
    case Accounts.create_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: page_path(conn, :index))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    render(conn, "show.html", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    user_ids = Accounts.get_user_id_list();
    changeset = Accounts.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset, user_ids: user_ids)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Accounts.get_user!(id)
    case Accounts.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    {:ok, _user} = Accounts.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: user_path(conn, :index))
  end
end

task_tracker_2/lib/task_tracker_2_web/views/user_view.ex
defmodule TaskTracker2Web.UserView do
  use TaskTracker2Web, :view
end

task_tracker_2/lib/task_tracker_2_web/templates/user/check.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

task_tracker_2/lib/task_tracker_2_web/templates/user/edit.html.eex
<h2>Edit User</h2>

<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :update, @user)) %>


<!--<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :show, @user)) %>-->

<!--<span><%= link "Back", to: user_path(@conn, :index) %></span>-->

task_tracker_2/lib/task_tracker_2_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :manager_id, class: "control-label" %>
    <%= select f, :manager_id, @user_ids, class: "form-control" %>
    <%= error_tag f, :manager_id %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
    <%= link "Back", to: page_path(@conn, :index), class: "btn btn-primary" %>
  </div>
<% end %>

task_tracker_2/lib/task_tracker_2_web/templates/user/index.html.eex
<h2>Listing Users</h2>


<table class="table">
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>ID</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.name %></td>
      <td><%= user.id %></td>

      <td class="text-right">
        <span><%= link "Show", to: user_path(@conn, :show, user), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: user_path(@conn, :edit, user), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= if @current_user do %>
  <span><%= link "Back", to: task_path(@conn, :index), class: "btn btn-primary" %></span>
<% else %>
  <span style="margin-right: 40px"><%= link "New User", to: user_path(@conn, :new), class: "btn btn-primary" %></span>
<% end %>

task_tracker_2/lib/task_tracker_2_web/templates/user/new.html.eex
<h2>New User</h2>

<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :create)) %>

<!--<span><%= link "Back", to: user_path(@conn, :index), class: "btn btn-primary" %></span>-->

task_tracker_2/lib/task_tracker_2_web/templates/user/show.html.eex
<h2>Show User</h2>

<ul>

  <li>
    <strong>Email:</strong>
    <%= @user.email %>
  </li>

  <li>
    <strong>Name:</strong>
    <%= @user.name %>
  </li>

  <li>
    <strong>ID:</strong>
    <%= @user.id %>
  </li>

  <li>
    <strong>Manager ID:</strong>
    <%= @user.manager_id %>
  </li>

</ul>

<span><%= link "Edit", to: user_path(@conn, :edit, @user) %></span>
<span><%= link "Back", to: user_path(@conn, :index), class: "btn btn-primary" %></span>