task_tracker_2/lib/task_tracker_2_web/router.ex
defmodule TaskTracker2Web.Router do
  use TaskTracker2Web, :router

  import TaskTracker2Web.Plugs.GetCurrentUser

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    # After fetch_session in the browser pipeline:
    plug :get_current_user
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Below the pipeline
  # def get_current_user(conn, _params) do
  #   # TODO: Move this function out of the router module.
  #   user_id = get_session(conn, :user_id)
  #   user = TaskTracker2.Accounts.get_user(user_id || -1)
  #   IO.puts "*************"
  #   IO.inspect user;
  #   assign(conn, :current_user, user)
  # end

  scope "/", TaskTracker2Web do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    resources "/tasks", TaskController do
      get "/slotedit", TaskController, :slot_edit, as: :slot_edit
    end
    # resources "/tasks", TaskController
    post "/session", SessionController, :create
    delete "/session", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", TaskTracker2Web do
    pipe_through :api
    resources "/slots", SlotController, except: [:new, :edit]
  end
end

task_tracker_2/lib/task_tracker_2/tracker/task.ex
defmodule TaskTracker2.Tracker.Task do
  use Ecto.Schema
  import Ecto.Changeset
  alias TaskTracker2.Tracker.Task
  alias TaskTracker2.Tracker.Slot

  schema "tasks" do
    field :description, :string
    field :is_finish, :boolean, default: false
    field :start_time, :integer, default: :os.system_time(:seconds)
    field :title, :string
    field :end_time, :integer, default: :os.system_time(:seconds)
    belongs_to :creator, TaskTracker2.Accounts.User
    belongs_to :assignee, TaskTracker2.Accounts.User
    has_many :task_slots, TaskTracker2.Tracker.Slot, foreign_key: :task_id
    # has_many :followers, through: [:task_slots, :task]


    timestamps()
  end

  @doc false
  def changeset(%Task{} = task, attrs) do
    task
        |> cast(attrs, [:title, :description, :start_time, :is_finish, :creator_id, :assignee_id, :end_time])
        |> foreign_key_constraint(:creator_id)
        |> foreign_key_constraint(:assignee_id)
        # |> foreign_key_constraint(:task_slots)
        |> validate_required([:title, :description, :start_time, :is_finish, :creator_id, :assignee_id, :end_time])
  end
end

task_tracker_2/lib/task_tracker_2_web/controllers/task_controller.ex
defmodule TaskTracker2Web.TaskController do
  use TaskTracker2Web, :controller

  alias TaskTracker2.Tracker
  alias TaskTracker2.Tracker.Task
  alias TaskTracker2.Accounts
  alias TaskTracker2.Accounts.User

# Enum.map(assignees, fn(n) -> Enum.reduce([n|>Map.get(:id), n|>Map.get(:name)], "-" ) end)
# time_slots|>Enum.reduce(0, f(x, acc) -> (acc+(x|>Map.get(:end_time)-x|>Map.get(:start_time))/60)|>round end);
# Enum.reduce(time_slots, 0, fn(x, acc) -> (x|>Map.get(:end_time) - x|>Map.get(:end_time))/60 + acc end)
  def index(conn, _params) do
    current_user = Map.get(conn.assigns, :current_user);
    assignees = Accounts.get_assignees_by_manager_id(current_user.id);
    tasks = Tracker.get_tasks_by_creator_id(current_user.id);
    works = Tracker.get_tasks_by_assignee_id(current_user.id);
    id_name_list = Enum.map(assignees, fn(n) -> Enum.join([n|>Map.get(:id), n|>Map.get(:name)], "-" ) end);

    render(conn, "index.html", tasks: tasks, id_name_list: id_name_list, this_assignees: assignees, works: works);
  end

  def new(conn, _params) do
    changeset = Tracker.change_task(%Task{})
    current_user = Map.get(conn.assigns, :current_user);
    assignees = Accounts.get_assignees_by_manager_id(current_user.id);
    id_list = Enum.map(assignees, fn(n) -> n|>Map.get(:id) end);
    render(conn, "new.html", changeset: changeset, this_assignees_ids: id_list)
  end

  def create(conn, %{"task" => task_params}) do
    task_params = Map.put(task_params, "start_time", :os.system_time(:second));
    case Tracker.create_task(task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task created successfully.")
        |> redirect(to: task_path(conn, :show, task))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    task = Tracker.get_task!(id)
    time_slots = Tracker.get_slots_by_id(id);
    # Map.get(x, :end_time)|>Kernel.-(Map.get(x, :start))
    duration_list = time_slots|>Enum.map(fn(x) -> get_duration(x) end);
    total_time = duration_list|>Enum.reduce(0, fn(x, acc) -> acc + Float.ceil(x/60) end);
    # total_time = Enum.reduce(time_slots, 0, fn(x, acc) -> (x|>Map.get(:end_time) - x|>Map.get(:end_time))/60 + acc end);
    render(conn, "show.html", task: task, time_slots: time_slots, total_time: total_time)
  end

  def get_duration(slot) do
    stime = slot|>Map.get(:start_time);
    etime = slot|>Map.get(:end_time);
    etime - stime;
  end

  # def check(conn,  %{"id" => id}) do
  #   task = Tracker.get_task!(id)
  #   changeset = Tracker.change_task(task)
  #   render(conn, "check.html", task: task, changeset: changeset)
  # end

  def edit(conn, %{"id" => id}) do
    task = Tracker.get_task!(id)
    time_slots = Tracker.get_slots_by_id(id);
    changeset = Tracker.change_task(task)
    render(conn, "edit.html", task: task, changeset: changeset, time_slots: time_slots)
  end

  def slot_edit(conn, %{"task_id" => id}) do
    slot = Tracker.get_slot!(id);
    changeset = Tracker.change_slot(slot);
    task_id = slot|>Map.get(:task_id);
    render(conn, "slotedit.html", slot: slot, changeset: changeset, task_id: task_id);
  end

  def update(conn, %{"id" => id, "task" => task_params}) do
    task = Tracker.get_task!(id)
    # time_slots = Trakcer.get_slots_by_id(id);
    isFinish = Map.get(task, :is_finish);

    if not isFinish do
      IO.puts "haha";
      IO.puts Integer.to_string(:os.system_time(:second));
      task_params = Map.put(task_params, "end_time", :os.system_time(:second));
      IO.puts Integer.to_string(task|>Map.get(:end_time));
    end

    case Tracker.update_task(task, task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task updated successfully.")
        |> redirect(to: task_path(conn, :show, task))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", task: task, changeset: changeset)
    end
  end


  def delete(conn, %{"id" => id}) do
    task = Tracker.get_task!(id)
    {:ok, _task} = Tracker.delete_task(task)

    conn
    |> put_flash(:info, "Task deleted successfully.")
    |> redirect(to: task_path(conn, :index))
  end
end

task_tracker_2/lib/task_tracker_2_web/views/task_view.ex
defmodule TaskTracker2Web.TaskView do
  use TaskTracker2Web, :view
end

task_tracker_2/lib/task_tracker_2_web/templates/task/check.html.eex
<script>
  window.slot_path = "<%= slot_path(@conn, :index) %>";
  window.current_task_id = "<%= @task.id %>";
</script>

<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>


  <!-- <div class="form-group" style="margin-top:30px">
    <%= label f, :assignee_id, class: "control-label" %>
    <%= text_input f, :assignee_id, class: "form-control" %>
    <%= error_tag f, :assignee_id %>
  </div>

  <span style="font-size:12px"><%= link "Check Available Assignees", to: user_path(@conn, :index) %></span> -->

  <div class="static-">
    <div class="form-group"  style="margin-top:30px;">
      <%= label f, :title, class: "control-label" %>
      <%= text_input f, :title, class: "form-control" %>
      <%= error_tag f, :title %>
    </div>

    <div class="form-group" style="margin-top:30px;">
      <%= label f, :description, class: "control-label" %>
      <%= textarea f, :description, class: "form-control" %>
      <%= error_tag f, :description %>
    </div>

    <div class="form-group">
      <%= hidden_input f, :creator_id, value: @task.creator_id, class: "form-control"%>
    </div>
  </div>
  
    <div class="form-group" style="margin-top:30px;">
      <%= label f, :is_finish, class: "control-label" %>
      <%= checkbox f, :is_finish, class: "checkbox" %>
      <%= error_tag f, :is_finish %>
    </div>


  <div class="form-group" style="margin-top:30px;">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

task_tracker_2/lib/task_tracker_2_web/templates/task/edit.html.eex
<h2>Edit Task</h2>

<%= render "check.html", Map.put(assigns, :action, task_path(@conn, :update, @task)) %>

<span><%= link "Back", to: task_path(@conn, :index) %></span>

task_tracker_2/lib/task_tracker_2_web/templates/task/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>


  <!-- <div class="form-group" style="margin-top:30px">
    <%= label f, :assignee_id, class: "control-label" %>
    <%= text_input f, :assignee_id, class: "form-control" %>
    <%= error_tag f, :assignee_id %>
  </div>

  <span style="font-size:12px"><%= link "Check Available Assignees", to: user_path(@conn, :index) %></span> -->


  <div class="form-group"  style="margin-top:30px;">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group" style="margin-top:30px;">
    <%= label f, :description, class: "control-label" %>
    <%= textarea f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= hidden_input f, :creator_id, value: @current_user.id, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= label f, :assignee_id, class: "control-label" %>
    <%= select f, :assignee_id, @this_assignees_ids, class: "form-control" %>
    <%= error_tag f, :assignee_id %>
  </div>

  <!-- <div class="form-group" style="margin-top:30px;">
    <%= label f, :is_finish, class: "control-label" %>
    <%= checkbox f, :is_finish, class: "checkbox" %>
    <%= error_tag f, :is_finish %>
  </div> -->
  <div class="form-group" style="margin-top:30px;">
    <%= submit "Submit", class: "btn btn-primary" %>
    <span><%= link "Back", to: task_path(@conn, :index), class: "btn btn-primary" %></span>
  </div>
<% end %>

task_tracker_2/lib/task_tracker_2_web/templates/task/index.html.eex
<style>

  th,td {
    text-align:center;
  }

  .btn {
    font-size: 12px;
  }

  .banner {
    margin-bottom: 20px;
  }
  .profile-col {
    float:left;
    font-size: 12px;
    display: inline-block;
    margin-right: 40px;
    border-right: 2px dotted grey;
    padding: 10px;
  }

  .profile-col span {
    font-weight: bold;
  }

  .task-list {
    clear:left;
    font-size: 12px;
    display: inline-block;
  }
</style>

<!-- <h5 class="banner">Profile</h5> -->
<h3>PROFILE</h3>
<div class="profile-col">
  <span>NAME: </span><br><%= @current_user.name %><br>

  <br>

  <span>EMAIL: </span><br><%= @current_user.email %><br>

  <br>

  <span>ID: </span><%= @current_user.id %><br>

  <br>

  <span>MANAGER: </span>
  <%= if @current_user.manager_id do %>
    <%= @current_user.manager_id %><br>
  <% else %>
    <%= "None" %>
  <% end %><br>

  <br>

  <span>ASSIGNEES: </span><br>
  <select>
    <%= for id_name_str <- @id_name_list do %>
      <option><%= id_name_str %></option>
    <% end %>
  </select>

  <br><br>

  <%= if Enum.count(@id_name_list) > 0 do %>
    <span class="new-task-link"><%= link "New Task", to: task_path(@conn, :new), class: "btn btn-primary" %></span>
  <% end %>

</div>

<div class="task-list">
  <h6>YOUR MONITOR:</h6>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Is Finish</th>
        <th>Complete Time(mins)</th>

        <th></th>
      </tr>
    </thead>
    <tbody>
  <%= for task <- @tasks do %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <!--<td><%= task.start_time %></td>-->
        <%= if task.is_finish do %>
          <td style="background-color:powderblue;"><%= "Yes" %></td>
        <% else %>
          <td style="background-color:#ffb6c1;"><%= "No" %></td>
        <% end %>

        <!-- <td><%= (((task.end_time-task.start_time)/60/15)|>round)*15 %></td> -->
        <%= if not task.is_finish do %>
          <td><%= "-" %></td>
        <% else %>
          <td><%= (((task.end_time-task.start_time)/60/15)|>round)*15 %></td>
        <% end %>

        <td class="text-right">
          <span><%= link "LOG", to: task_path(@conn, :show, task), class: "btn btn-default btn-xs" %></span>
          <%= if not task.is_finish and @current_user.id==task.assignee_id do %>
            <span><%= link "edit", to: task_path(@conn, :edit, task), class: "btn btn-default btn-xs" %></span>
          <% end %>
          <span><%= link "Delete", to: task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
        </td>
      </tr>
  <% end %>
    </tbody>
  </table>
  <br>
  <h6>YOUR WORK LOG:</h6>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Is Finish</th>
        <th>Complete Time(mins)</th>

        <th></th>
      </tr>
    </thead>
    <tbody>
  <%= for task <- @works do %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <!--<td><%= task.start_time %></td>-->
        <%= if task.is_finish do %>
          <td style="background-color:powderblue;"><%= "Yes" %></td>
        <% else %>
          <td style="background-color:#ffb6c1;"><%= "No" %></td>
        <% end %>

        <!-- <td><%= (((task.end_time-task.start_time)/60/15)|>round)*15 %></td> -->
        <%= if not task.is_finish do %>
          <td><%= "-" %></td>
        <% else %>
          <td><%= (((task.end_time-task.start_time)/60/15)|>round)*15 %></td>
        <% end %>

        <td class="text-right">
          <span><%= link "LOG", to: task_path(@conn, :show, task), class: "btn btn-default btn-xs" %></span>
          <%= if not task.is_finish and @current_user.id==task.assignee_id do %>
            <span><%= link "edit", to: task_path(@conn, :edit, task), class: "btn btn-default btn-xs" %></span>
          <% end %>
        </td>
      </tr>
  <% end %>
    </tbody>
  </table>
</div>

task_tracker_2/lib/task_tracker_2_web/templates/task/new.html.eex
<h2>New Task</h2>

<%= render "form.html", Map.put(assigns, :action, task_path(@conn, :create)) %>

task_tracker_2/lib/task_tracker_2_web/templates/task/show.html.eex
<script>
  window.slot_path = "<%= slot_path(@conn, :index) %>";
  window.current_task_id = "<%= @task.id %>";
</script>

<style>
  .work-time-log {
    font-size: 15px;
    display: inline-block;
    clear: left;
  }
  .static-info {
    font-size: 15px;
    display: inline-block;
    float: left;
    border-right: 2px dotted grey;
    margin-right: 10px;
    padding: 10px;
  }
  ul {
    list-style-type: none;
  }
  th, td {
    text-align: center;
  }
</style>

<h3>Show Task</h3>

<div class="static-info">

    <strong>Title:</strong><br>
    <%= @task.title %><br>

    <br>

    <strong>Description:</strong><br>
    <%= @task.description %><br>

    <br>

    <strong>Create Time:</strong><br>
    <!-- <%= ((:os.system_time(:second)-@task.start_time)/60)|>round %> mins ago -->
    <%= @task.start_time|>DateTime.from_unix|>elem(1)|>Map.get(:year) %>/
    <%= @task.start_time|>DateTime.from_unix|>elem(1)|>Map.get(:month) %>/
    <%= @task.start_time|>DateTime.from_unix|>elem(1)|>Map.get(:day) %> -
    <%= @task.start_time|>DateTime.from_unix|>elem(1)|>Map.get(:hour) %>:
    <%= @task.start_time|>DateTime.from_unix|>elem(1)|>Map.get(:minute) %>:
    <%= @task.start_time|>DateTime.from_unix|>elem(1)|>Map.get(:second) %><br>

    <br>

    <strong>End time:</strong><br>
    <%= if @task.is_finish do %>
      <%= @task.end_time|>DateTime.from_unix|>elem(1)|>Map.get(:year) %>/
      <%= @task.end_time|>DateTime.from_unix|>elem(1)|>Map.get(:month) %>/
      <%= @task.end_time|>DateTime.from_unix|>elem(1)|>Map.get(:day) %> -
      <%= @task.end_time|>DateTime.from_unix|>elem(1)|>Map.get(:hour) %>:
      <%= @task.end_time|>DateTime.from_unix|>elem(1)|>Map.get(:minute) %>:
      <%= @task.end_time|>DateTime.from_unix|>elem(1)|>Map.get(:second) %>
    <% else %>
      <%= "-" %>
    <% end %><br>

    <br>

    <strong>Total Work Time:</strong><br>
    <%= if @total_time do %>
      <%= @total_time %> mins
    <% else %>
      <%= "-" %>
    <% end %><br>

    <br>

    <strong>Is finish:</strong><br>
    <%= @task.is_finish %><br>

    <br>

    <strong>Creator:</strong><br>
    <%= @task.creator.name %><br>

    <br>

    <strong>Assignee:</strong><br>
    <%= @task.assignee.name %>

    <br><br>

    <%= if not @task.is_finish and @task.assignee_id == @current_user.id do %>
        <button class="slot-button btn btn-primary"></button>
    <% end %>

    <br><br>

    <span><%= link "Back", to: task_path(@conn, :index), class: "btn btn-primary" %></span>

</div>

<div class="work-time-log">
  <table class="table">
    <thead>
      <tr>
        <th>slot No.</th>
        <th>start time</th>
        <th>end time</th>
        <th>duration(mins)</th>

        <th></th>
      </tr>
    </thead>
    <tbody>
        <%= for slot <- @time_slots do %>
          <tr>
            <td><%= slot.id %></td>
            <td>
              <%= slot.start_time|>DateTime.from_unix|>elem(1)|>Map.get(:year) %>/
              <%= slot.start_time|>DateTime.from_unix|>elem(1)|>Map.get(:month) %>/
              <%= slot.start_time|>DateTime.from_unix|>elem(1)|>Map.get(:day) %> -
              <%= slot.start_time|>DateTime.from_unix|>elem(1)|>Map.get(:hour) %>:
              <%= slot.start_time|>DateTime.from_unix|>elem(1)|>Map.get(:minute) %>:
              <%= slot.start_time|>DateTime.from_unix|>elem(1)|>Map.get(:second) %>
            </td>
            <td>
              <%= slot.end_time|>DateTime.from_unix|>elem(1)|>Map.get(:year) %>/
              <%= slot.end_time|>DateTime.from_unix|>elem(1)|>Map.get(:month) %>/
              <%= slot.end_time|>DateTime.from_unix|>elem(1)|>Map.get(:day) %> -
              <%= slot.end_time|>DateTime.from_unix|>elem(1)|>Map.get(:hour) %>:
              <%= slot.end_time|>DateTime.from_unix|>elem(1)|>Map.get(:minute) %>:
              <%= slot.end_time|>DateTime.from_unix|>elem(1)|>Map.get(:second) %>
            </td>
            <td><%= Float.ceil((slot.end_time - slot.start_time)/60) %></td>
            <td><span><%= link "Edit", to: task_slot_edit_path(@conn, :slot_edit, slot), class: "btn btn-danger btn-xs" %></span></td>

          </tr>
        <% end %>
    </tbody>
  </table>
</div>

task_tracker_2/lib/task_tracker_2_web/templates/task/slotedit.html.eex
<h2>Edit Slot</h2>

<%= render "slotform.html", Map.put(assigns, :action, slot_path(@conn, :update, @slot)) %>

task_tracker_2/lib/task_tracker_2_web/templates/task/slotform.html.eex
<style>
  .start-time-edit {
    float: left;
    display: inline-block;
    margin-right: 80px;
  }
  .end-time-edit {
    clear: left;
    display: inline-block;
    margin-right: 80px;
  }
  .btn {
    margin-right: 40px;
  }
</style>

<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>


  <!-- <div class="form-group" style="margin-top:30px">
    <%= label f, :assignee_id, class: "control-label" %>
    <%= text_input f, :assignee_id, class: "form-control" %>
    <%= error_tag f, :assignee_id %>
  </div>

  <span style="font-size:12px"><%= link "Check Available Assignees", to: user_path(@conn, :index) %></span> -->

  <div class="start-time-edit">
    <div class="form-group"  style="margin-top:30px;">
      <%= label f, :start_year, class: "control-label" %>
      <%= select f, :start_year, 1970..2018, class: "form-control" %>
      <%= error_tag f, :start_year %>
    </div>

    <div class="form-group"  style="margin-top:30px;">
      <%= label f, :start_month, class: "control-label" %>
      <%= select f, :start_month, 1..12, class: "form-control" %>
      <%= error_tag f, :start_month %>
    </div>

    <div class="form-group"  style="margin-top:30px;">
      <%= label f, :start_day, class: "control-label" %>
      <%= select f, :start_day, 1..31, class: "form-control" %>
      <%= error_tag f, :start_day %>
    </div>

    <div class="form-group"  style="margin-top:30px;">
      <%= label f, :start_hour, class: "control-label" %>
      <%= select f, :start_hour, 0..23, class: "form-control" %>
      <%= error_tag f, :start_hour %>
    </div>
  </div>

  <div class="end-time-edit">
    <div class="form-group"  style="margin-top:30px;">
      <%= label f, :end_year, class: "control-label" %>
      <%= select f, :end_year, 1970..2018, class: "form-control" %>
      <%= error_tag f, :end_year %>
    </div>

    <div class="form-group"  style="margin-top:30px;">
      <%= label f, :end_month, class: "control-label" %>
      <%= select f, :end_month, 1..12, class: "form-control" %>
      <%= error_tag f, :end_month %>
    </div>

    <div class="form-group"  style="margin-top:30px;">
      <%= label f, :end_day, class: "control-label" %>
      <%= select f, :end_day, 1..31, class: "form-control" %>
      <%= error_tag f, :end_day %>
    </div>

    <div class="form-group"  style="margin-top:30px;">
      <%= label f, :end_hour, class: "control-label" %>
      <%= select f, :end_hour, 0..23, class: "form-control" %>
      <%= error_tag f, :end_hour %>
    </div>
  </div>

  <!-- <div class="form-group" style="margin-top:30px;">
    <%= label f, :is_finish, class: "control-label" %>
    <%= checkbox f, :is_finish, class: "checkbox" %>
    <%= error_tag f, :is_finish %>
  </div> -->
  <div class="form-group" style="margin-top:30px;">
    <%= submit "Submit", class: "btn btn-primary" %>
    <span><%= link "Back", to: task_path(@conn, :show, @task_id), class: "btn btn-primary" %></span>
  </div>
<% end %>